cupon_shopping_cart_addtocart:
    path:     /addtocart/{id}
    defaults: { _controller: CuponShoppingCartBundle:Default:addToCart }
cupon_shopping_cart_removefromcart:
    path:     /removefromcart/{id}
    defaults: { _controller: CuponShoppingCartBundle:Default:removeFromCart }