cupon_shopping_cart_addtocart:
    path:     /addtocart/{id}
    defaults: { _controller: cupon_shopping_cart.default_controller:addToCartAction }
cupon_shopping_cart_removefromcart:
    path:     /removefromcart/{id}
    defaults: { _controller: cupon_shopping_cart.default_controller:removeFromCartAction }
cupon_shopping_cart_showcart:
    path:     /showcart
    defaults: { _controller: cupon_shopping_cart.default_controller:renderShoppingCart, display: full }